version: '3.7'
services:
  windows-dev:
    image: nakayamaatsushi/fq1150-vsm-build-windows:${WINDOWS_TAG}
    volumes:
      - ".:/home/build"
  linux-dev:
    image: nakayamaatsushi/fq1150-vsm-build-linux:${LINUX_TAG}
    volumes:
      - ".:/home/build"
    ports:
      - "0.0.0.0:14550:14550/udp"
    command: "bash -c 'cd build/linux && mkdir -p /opt/vsm-sdk/linux/log && ./vsm-ardupilot'"
